name: 'GitHub Comment'
description: 'GitHub Action for posting GitHub comments'
inputs:
  message:
    description: 'message'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
