name: 'Google Cloud Run Deployment'
description: 'GitHub Action for making deployments with Google Cloud Run'
inputs:
  alias:
    description: 'alias'
    required: true
  stage:
    description: 'stage'
    required: true
    default: 'canary'
  region:
    description: 'region'
    required: true
    default: 'eu'
  is_public:
    description: 'is_public'
    default: false
  flags:
    description: 'flags'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.stage }}
    - ${{ inputs.region }}
    - ${{ inputs.is_public }}
    - ${{ inputs.flags }}