name: 'Google Cloud Run Deployment'
description: 'GitHub Action for making deployments with Google Cloud Run'
inputs:
  alias:
    description: 'alias'
    required: true
  is_public:
    description: 'is_public'
    default: true
  flags:
    description: 'flags'
  log_level:
    description: 'log level'
    default: 'info'
  log_format:
    description: 'log format'
    default: 'json'
  add_iam_binding:
    description: 'add iam binding'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.is_public }}
    - ${{ inputs.flags }}
    - ${{ inputs.log_level }}
    - ${{ inputs.log_format }}
    - ${{ inputs.add_iam_binding }}