name: 'Google Cloud Run Deployment'
description: 'GitHub Action for making deployments with Google Cloud Run'
inputs:
  alias:
    description: 'alias'
    required: true
  async:
    description: 'return immediately, without waiting for the operation in progress to complete'
    default: false
  is_public:
    description: 'whether to allow unauthenticated access to the service'
    default: true
  env_vars:
    description: 'environment variables that will be injected into the container'
  log_level:
    description: 'log level'
    default: 'info'
  log_format:
    description: 'log format'
    default: 'json'
  add_iam_binding:
    description: 'whether to add iam binding or not'
    default: false
  max_instances:
    description: 'max instances'
    default: 'default'
  memory:
    description: 'memory'
    default: '256Mi'
  concurrency:
    description: 'concurrency'
    default: '0'
  timeout:
    description: 'timeout (max 15m)'
    default: '5m'
outputs:
  url:
    description: 'The deployment url'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.is_public }}
    - ${{ inputs.env_vars }}
    - ${{ inputs.log_level }}
    - ${{ inputs.log_format }}
    - ${{ inputs.add_iam_binding }}
    - ${{ inputs.max_instances }}
    - ${{ inputs.memory }}
    - ${{ inputs.concurrency }}
    - ${{ inputs.timeout }}
    - ${{ inputs.async }}