name: 'Google Cloud Run Deployment'
description: 'GitHub Action for making deployments with Google Cloud Run'
inputs:
  alias:
    description: 'alias'
    required: true
  stage:
    description: 'stage'
    default: 'canary'
  region:
    description: 'region'
    default: 'eu'
  is_public:
    description: 'is_public'
    default: true
  flags:
    description: 'flags'
  subscriptions:
    description: 'subscriptions'
    required: false
  log_level:
    description: 'log level'
    default: 'info'
  log_format:
    description: 'log format'
    default: 'json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.stage }}
    - ${{ inputs.region }}
    - ${{ inputs.is_public }}
    - ${{ inputs.flags }}
    - ${{ inputs.subscriptions }}
    - ${{ inputs.log_level }}
    - ${{ inputs.log_format }}