name: "Wrangler"
description: "GitHub Action for making deployments with Wrangler"
inputs:
  apiToken:
    description: "Your Cloudflare API Token"
  vars:
    description: "Injects environment variables"
    required: false
  use_runtime_config:
    description: "whether to inject runtime config variables as environment variables during the build process"
    default: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.apiToken }}
    - ${{ inputs.vars }}
    - ${{ inputs.use_runtime_config }}
