name: 'Zeit Now'
description: 'GitHub Action for making deployments with Zeit Now'
inputs:
  alias:
    description: 'Domain name'
    required: true
  name:
    description: 'String name for the deployment'
    required: true
  prod:
    description: 'Is it a production deployment?'
    required: false
    default: false
  force:
    description: 'Forces a new build even if artefact did not change'
    required: false
    default: false
  vars:
    description: 'Injects environment variables'
    required: false
  use_runtime_config:
    description: 'whether to inject runtime config variables as environment variables during the build process'
    default: true
outputs:
  url:
    description: 'The deployment url'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.name }}
    - ${{ inputs.prod }}
    - ${{ inputs.force }}
    - ${{ inputs.vars }}
    - ${{ inputs.use_runtime_config }}