name: 'Zeit Now'
description: 'GitHub Action for making deployments with Zeit Now'
inputs:
  alias:
    description: 'alias'
    required: true
  name:
    description: 'name'
    required: true
  env:
    description: 'env file'
    required: false
  prod:
    description: 'prod'
    required: false
    default: false
outputs:
  url:
    description: 'The deployment url'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.name }}
    - ${{ inputs.env }}
    - ${{ inputs.prod }}