name: 'Zeit Now'
description: 'GitHub Action for making deployments with Zeit Now'
inputs:
  alias:
    description: 'alias'
    required: true
  env:
    description: 'environment'
    required: true
    default: 'canary'
  region:
    description: 'region'
    required: true
    default: 'eu'
# outputs:
#   time:
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.env }}
    - ${{ inputs.region }}