name: 'Zeit Now'
description: 'GitHub Action for making deployments with Zeit Now'
inputs:
  alias:
    description: 'alias'
    required: true
  stage:
    description: 'stage'
    required: true
    default: 'canary'
  region:
    description: 'region'
    required: true
    default: 'eu'
  prod:
    description: 'prod'
    required: false
    default: false
outputs:
  url:
    description: 'The deployment url'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.stage }}
    - ${{ inputs.region }}
    - ${{ inputs.prod }}