name: "Dotenv"
description: "GitHub Action for generating dotenv files"
inputs:
  vars:
    description: "Injects environment variables"
    required: false
  use_runtime_config:
    description: "whether to inject runtime config variables as environment variables during the build process"
    default: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.vars }}
    - ${{ inputs.use_runtime_config }}
