name: 'Remote testing'
description: 'GitHub Action for running remote tests'
inputs:
  url:
    description: 'test url'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
