name: 'Remote testing'
description: 'GitHub Action for running remote tests'
inputs:
  stage:
    description: 'stage'
    required: true
    default: 'canary'
  region:
    description: 'region'
    required: true
    default: 'eu'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stage }}
    - ${{ inputs.region }}